apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-token-rotator-role
  namespace: finance
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-auth-finance-token"]
    verbs: ["get", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
